apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: coronavirus-tracker
spec:
  selector:
    app: coronavirus-tracker
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
  type: LoadBalancer # type of the service. LoadBalancer indicates that our service will be external.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coronavirus-tracker
  labels:
    app: coronavirus-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coronavirus-tracker
  template:
    metadata:
      labels:
        app: coronavirus-tracker
    spec:
      containers:
        - name: coronavirus-tracker
          image: lylio/coronavirus-tracker:latest
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster